feat: add node 20
Byzanteam/actions-runner-image pull request #1
Opened 2024-09-13 08:47 UTC by YkeLit

2024-09-13 08:56 UTC, fahchen commented on .github/workflows/image-build.yml
> +          dockerfile: ./actions-runner-image/images/Dockerfile
这里的 tag 的计算方式是怎么定的啊？fe-build-image 那里主要是给前端项目用的规则

2024-09-13 08:56 UTC, fahchen commented on images/actions-runner/Dockerfile
这个 rope 还会放其他 image 不？如果不会就不用放文件夹里面了

2024-09-13 09:05 UTC, YkeLit commented on .github/workflows/image-build.yml
> +          dockerfile: ./actions-runner-image/images/Dockerfile
tag 默认是repo: sha

2024-09-13 09:48 UTC, fahchen requested changes

2024-09-13 09:48 UTC, fahchen commented on images/actions-runner/Dockerfile
如果有后面的这里的 tag 就不能这么定哦
https://github.com/Byzanteam/actions-runner-image/pull/1/files#r1758470106

2024-09-13 09:57 UTC, YkeLit commented on images/actions-runner/Dockerfile
这样可以不，有个默认的latest，然后还有个和 原版 actions-runner 一样的tag

2024-09-13 12:15 UTC, fahchen commented on .github/workflows/image-build.yml
> +                - nodeselector=kubernetes.io/arch=arm64
这个可以用 `setup-multi-form-buildx`

2024-09-13 12:15 UTC, fahchen commented on .github/workflows/image-build.yml
> +            APP_REVISION=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.revision'] }}
```suggestion
```

2024-09-13 12:15 UTC, fahchen commented on .github/workflows/image-build.yml
> +          cache-to: type=registry,ref=ghcr.io/byzanteam/actions-runner-image:buildcache,mode=max
```suggestion
          cache-from: type=registry,ref=ghcr.io/byzanteam/actions-runner:buildcache
          cache-to: type=registry,ref=ghcr.io/byzanteam/actions-runner:buildcache,mode=max
```

2024-09-13 12:15 UTC, fahchen commented on .github/workflows/image-build.yml
> +            ghcr.io/byzanteam/project_man
```suggestion
            ghcr.io/byzanteam/actions-runner
```

2024-09-13 12:15 UTC, fahchen commented on .github/workflows/image-build.yml
> +            ${{ steps.acr.outputs.hostname }}/${{ steps.acr.outputs.namespace }}/project_man
这个不对

2024-09-14 03:22 UTC, YkeLit commented
https://github.com/Byzanteam/actions-runner-image/actions/runs/10859075046
打包的结果

2024-09-14 03:37 UTC, fahchen approved these changes

2024-09-14 03:52 UTC, merged